=== EuPathDB-Infra/WDK/Service/doc/schema/wdk/users/steps/analyses/post-response.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "analysisName": {
      "type": "string"
    },
    "answerValueHash": {
      "type": "string"
    },
    "formParams": {
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "analysisId": {
      "type": "integer"
    },
    "stepId": {
      "type": "integer"
    },
    "displayName": {
      "type": "string"
    },
    "shortDescription": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "hasParams": {
      "type": "boolean"
    },
    "status": {
      "type": "string"
    },
    "invalidStepReason": {
      "type": ["string", "null"]
    }
  },
  "required": [
    "analysisName",
    "answerValueHash",
    "formParams",
    "analysisId",
    "stepId",
    "displayName",
    "shortDescription",
    "description",
    "hasParams",
    "status",
    "invalidStepReason"
  ]
}

=== EuPathDB-Infra/WDK/Service/doc/raml/includes/example/StepAnalysisInstanceSummary.example.json
{
  "analysisName": "some analysis name",
  "analysisId": 1234,
  "stepId": 1234,
  "answerValueHash": "MD5 hash",
  "displayName": "some customizable name",
  "shortDescription": "a short description",
  "description": "a longer description",
  "hasParams": true,
  "status": "a status?",
  "formParams": {
    "param name": [
      "some",
      "param",
      "values"
    ]
  },
  "invalidStepReason": null
}
